import { Router } from 'express';
import { router as authRouter } from './auth.js';
import { router as missingRouter } from './missing-persons.js';
import { router as sightingRouter } from './sightings.js';
import { router as alertsRouter } from './alerts.js';
import { router as volunteerRouter } from './volunteers.js';
import { router as statsRouter } from './stats.js';
import { router as favoritesRouter } from './favorites.js';
import { router as adminRouter } from './admin.js';
import { router as reportsRouter } from './reports.js';
import { router as uploadRouter } from './upload.js';
import { router as chatRouter } from './chat.js';
import { router as usersRouter } from './users.js';
import { adminUsersRouter } from './users-admin.js';
import { router as logsRouter } from './logs.js';
import { router as userHistoryRouter } from './user-history.js';
import { router as badgesRouter } from './badges.js';
import { router as authorityChatRouter } from './authority-chat.js';
import { router as authoritiesRouter } from './authorities.js';
import { router as duplicatesRouter } from './duplicates.js';
import { router as partnersRouter } from './partners.js';
import { router as imageAnalysisRouter } from './image-analysis.js';
import { router as institutionalContentRouter } from './institutional-content.js';
import { router as systemConfigRouter } from './system-config.js';
import { router as deletedCasesRouter } from './deleted-cases.js';
import { router as backupsRouter } from './backups.js';
import { router as announcementsRouter } from './announcements.js';
import { router as notificationConfigRouter } from './notification-config.js';

export const router = Router();

router.use('/auth', authRouter);
router.use('/missing-persons', missingRouter);
router.use('/sightings', sightingRouter);
router.use('/alerts', alertsRouter);
router.use('/volunteers', volunteerRouter);
router.use('/stats', statsRouter);
router.use('/favorites', favoritesRouter);
router.use('/admin', adminRouter);
router.use('/reports', reportsRouter);
router.use('/upload', uploadRouter);
router.use('/chat', chatRouter);
router.use('/users', usersRouter);
router.use('/admin/users', adminUsersRouter);
router.use('/admin/logs', logsRouter);
router.use('/user/history', userHistoryRouter);
router.use('/badges', badgesRouter);
router.use('/authority-chat', authorityChatRouter);
router.use('/authorities', authoritiesRouter);
router.use('/duplicates', duplicatesRouter);
router.use('/partners', partnersRouter);
router.use('/image-analysis', imageAnalysisRouter);
router.use('/institutional-content', institutionalContentRouter);
router.use('/system-config', systemConfigRouter);
router.use('/deleted-cases', deletedCasesRouter);
router.use('/backups', backupsRouter);
router.use('/announcements', announcementsRouter);
router.use('/notification-config', notificationConfigRouter);


